### ISSUE TITLE
Crash When Removing Glasses From Bobble Slot

### ISSUE THREAD

**Issue by gudenau** [StarChasers/OCGlasses#56]
When I removed my glasses from the bobbles slot the server crashed, client was unaffected.

This caused the glasses to be deleted from the world.

Stack trace:
```
[13:20:17] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@3b0837b2:
java.lang.NullPointerException: null
        at com.bymarcin.openglasses.surface.ServerSurface$EventHandler.updatePlayer(ServerSurface.java:59) ~[ServerSurface$EventHandler.class:?]
        at com.bymarcin.openglasses.surface.ServerSurface$EventHandler.tickStart(ServerSurface.java:47) ~[ServerSurface$EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1360_EventHandler_tickStart_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by ben-mkiv** [comment]
Thanks for your report. NVM, probably figured out. Uploading 2.0.6 to curseforge now

**Comment by ben-mkiv** [comment]
Closing this, please open a new Issue if something like this happens again.
