### ISSUE TITLE
Crash when setting a specific item in Item2D

### ISSUE THREAD

**Issue by ghost** [StarChasers/OCGlasses#94]
**Describe the bug**
Minecraft crashes when setting "botania:specialflower" to Item2D

**In which environment did the Bug appear?**
Single with Twitch App

**To Reproduce**
Create an Item2D widget and use setItem

**Screenshots / Code Snippet**
![2020-06-07_05 55 47](https://user-images.githubusercontent.com/66514293/83954513-dae7df80-a884-11ea-82e6-9a62778071ca.png)
Crash when I press Enter

<details>
<summary>crash report</summary>
<pre>
<code>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 6/7/20 5:56 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at vazkii.botania.client.model.SpecialFlowerModel$SpecialFlowerBakedModel.func_188616_a(SpecialFlowerModel.java:171)
	at ben_mkiv.rendertoolkit.common.widgets.component.common.ItemIcon$RenderableItemIcon.render(ItemIcon.java:118)
	at ben_mkiv.rendertoolkit.surface.ClientSurface.renderWidget(ClientSurface.java:138)
	at ben_mkiv.rendertoolkit.surface.ClientSurface.renderWidget(ClientSurface.java:133)
	at com.bymarcin.openglasses.surface.OCClientSurface.renderWidgets(OCClientSurface.java:233)
	at com.bymarcin.openglasses.surface.OCClientSurface.renderOverlay(OCClientSurface.java:129)
	at com.bymarcin.openglasses.event.minecraft.client.ClientRenderEvents.onRenderGameOverlay(ClientRenderEvents.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_123_ClientRenderEvents_onRenderGameOverlay_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:135)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at vazkii.botania.client.model.SpecialFlowerModel$SpecialFlowerBakedModel.func_188616_a(SpecialFlowerModel.java:171)
	at ben_mkiv.rendertoolkit.common.widgets.component.common.ItemIcon$RenderableItemIcon.render(ItemIcon.java:118)
	at ben_mkiv.rendertoolkit.surface.ClientSurface.renderWidget(ClientSurface.java:138)
	at ben_mkiv.rendertoolkit.surface.ClientSurface.renderWidget(ClientSurface.java:133)
	at com.bymarcin.openglasses.surface.OCClientSurface.renderWidgets(OCClientSurface.java:233)
	at com.bymarcin.openglasses.surface.OCClientSurface.renderOverlay(OCClientSurface.java:129)
	at com.bymarcin.openglasses.event.minecraft.client.ClientRenderEvents.onRenderGameOverlay(ClientRenderEvents.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_123_ClientRenderEvents_onRenderGameOverlay_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:135)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['cafemq'/145, l='MpServer', x=40.74, y=4.00, z=975.61]]
	Chunk stats: MultiplayerChunkCache: 531, 531
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (45,4,973), Chunk: (at 13,0,13 in 2,60; contains blocks 32,0,960 to 47,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 6917 game time, 6917 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 59 total; [EntitySlime['Slime'/319108, l='MpServer', x=-33.22, y=4.00, z=999.38], EntitySlime['Slime'/383623, l='MpServer', x=32.79, y=4.00, z=1013.60], EntitySlime['Slime'/466058, l='MpServer', x=-3.32, y=4.00, z=1000.67], EntitySlime['Slime'/248978, l='MpServer', x=3.42, y=4.00, z=957.60], EntitySlime['Slime'/186006, l='MpServer', x=54.59, y=4.67, z=1050.36], EntitySlime['Slime'/164245, l='MpServer', x=52.70, y=4.00, z=966.21], EntitySlime['Slime'/376477, l='MpServer', x=-31.20, y=4.50, z=997.76], EntitySlime['Slime'/104095, l='MpServer', x=23.00, y=4.75, z=972.41], EntitySlime['Slime'/231206, l='MpServer', x=36.96, y=4.72, z=996.57], EntitySlime['Slime'/40, l='MpServer', x=36.74, y=5.17, z=992.96], EntitySlime['Slime'/41, l='MpServer', x=-34.95, y=4.28, z=1000.94], EntitySlime['Slime'/461614, l='MpServer', x=7.21, y=4.00, z=1013.39], EntityPlayerSP['cafemq'/145, l='MpServer', x=40.74, y=4.00, z=975.61], EntitySlime['Slime'/46, l='MpServer', x=33.09, y=4.50, z=958.59], EntitySlime['Slime'/51, l='MpServer', x=27.40, y=4.00, z=984.30], EntityCow['Cow'/56, l='MpServer', x=47.36, y=4.00, z=922.72], EntitySheep['Sheep'/57, l='MpServer', x=47.50, y=4.00, z=924.50], EntitySlime['Slime'/132920, l='MpServer', x=-17.18, y=4.00, z=1009.67], EntitySlime['Slime'/293566, l='MpServer', x=32.61, y=4.00, z=1011.60], EntitySheep['Sheep'/59, l='MpServer', x=39.23, y=4.00, z=977.52], EntitySlime['Slime'/2747, l='MpServer', x=52.06, y=4.00, z=1004.06], EntitySlime['Slime'/290751, l='MpServer', x=31.61, y=5.17, z=1005.24], EntitySlime['Slime'/360894, l='MpServer', x=-22.98, y=4.00, z=999.96], EntitySheep['Sheep'/60, l='MpServer', x=32.33, y=4.00, z=1010.74], EntitySheep['Sheep'/61, l='MpServer', x=45.75, y=4.00, z=1010.08], EntitySlime['Slime'/63, l='MpServer', x=100.39, y=4.00, z=1016.56], EntitySlime['Slime'/64, l='MpServer', x=31.73, y=4.00, z=992.12], EntityChicken['Chicken'/66, l='MpServer', x=47.97, y=4.00, z=1048.42], EntityChicken['Chicken'/67, l='MpServer', x=46.92, y=4.00, z=1051.58], EntitySlime['Slime'/437061, l='MpServer', x=38.12, y=4.00, z=916.02], EntityChicken['Chicken'/68, l='MpServer', x=41.50, y=4.00, z=1055.50], EntityHorse['Horse'/69, l='MpServer', x=47.98, y=4.00, z=1051.59], EntitySlime['Slime'/382543, l='MpServer', x=28.12, y=4.42, z=1019.03], EntitySlime['Slime'/328265, l='MpServer', x=-17.99, y=4.00, z=979.73], EntityChicken['Chicken'/78, l='MpServer', x=63.50, y=4.00, z=896.50], EntityCow['Cow'/79, l='MpServer', x=58.37, y=4.00, z=907.85], EntityCow['Cow'/80, l='MpServer', x=57.16, y=4.00, z=928.24], EntitySheep['Sheep'/82, l='MpServer', x=53.00, y=4.00, z=1010.78], EntitySlime['Slime'/444510, l='MpServer', x=-10.96, y=5.10, z=940.47], EntitySlime['Slime'/288346, l='MpServer', x=15.29, y=4.00, z=994.36], EntityCow['Cow'/95, l='MpServer', x=87.50, y=4.00, z=900.50], EntitySlime['Slime'/454617, l='MpServer', x=8.01, y=4.00, z=1025.54], EntityCow['Cow'/96, l='MpServer', x=85.66, y=4.00, z=904.95], EntitySlime['Slime'/454631, l='MpServer', x=62.28, y=5.10, z=1001.58], EntityCow['Cow'/97, l='MpServer', x=87.50, y=4.00, z=896.50], EntityChicken['Chicken'/98, l='MpServer', x=93.50, y=4.00, z=902.50], EntitySlime['Slime'/430051, l='MpServer', x=30.94, y=4.00, z=1006.48], EntitySlime['Slime'/337378, l='MpServer', x=-5.67, y=5.17, z=965.30], EntitySheep['Sheep'/106, l='MpServer', x=98.93, y=4.00, z=932.26], EntitySheep['Sheep'/107, l='MpServer', x=97.77, y=4.00, z=934.64], EntitySlime['Slime'/289647, l='MpServer', x=-16.23, y=4.92, z=1012.87], EntitySheep['Sheep'/108, l='MpServer', x=98.68, y=4.00, z=943.18], EntitySheep['Sheep'/109, l='MpServer', x=111.28, y=4.00, z=925.78], EntitySlime['Slime'/493800, l='MpServer', x=-10.36, y=4.00, z=933.13], EntitySlime['Slime'/348533, l='MpServer', x=16.66, y=4.00, z=1034.21], EntitySlime['Slime'/53105, l='MpServer', x=72.86, y=5.17, z=960.40], EntitySlime['Slime'/323569, l='MpServer', x=55.76, y=4.95, z=1010.95], EntitySlime['Slime'/451962, l='MpServer', x=93.75, y=5.17, z=1049.41], EntitySlime['Slime'/400377, l='MpServer', x=22.48, y=4.00, z=1030.29]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 16418793840 bytes (15658 MB) / 20726153216 bytes (19766 MB) up to 22906667008 bytes (21845 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m -Xmx24576m -Xms12288m -XX:PermSize=1536m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                               | Signature                                |
	|:------ |:------------------ |:------------ |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                        | None                                     |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                        | None                                     |
	| LCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core | 1.7.5.192    | minecraft.jar                        | None                                     |
	| LCHIJA | baubles            | 1.5.2        | Baubles-1.12-1.5.2.jar               | None                                     |
	| LCHIJA | jei                | 4.15.0.291   | jei_1.12.2-4.15.0.291.jar            | None                                     |
	| LCHIJA | botania            | r1.10-363    | Botania r1.10-363.jar                | None                                     |
	| LCHIJA | opencomputers      | 1.7.5.192    | OpenComputers-MC1.12.2-1.7.5.192.jar | None                                     |
	| LCHIJA | rendertoolkit      | 1.3.7        | Commons0815-1.12.2-1.3.7.jar         | None                                     |
	| LCHIJA | guitoolkit         | 1.3.7        | Commons0815-1.12.2-1.3.7.jar         | None                                     |
	| LCHIJA | commons0815        | 1.3.7        | Commons0815-1.12.2-1.3.7.jar         | None                                     |
	| LCHIJA | openglasses        | @VERSION@-50 | OpenGlasses-MC1.12.2-2.2-50.jar      | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.59' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
</code>
</pre>
</details>

**Minecraft:**
 - Minecraft Version (Minecraft 1.12.2)
 - Forge Version (forge-14.23.5.2854)
 - OpenGlasses (OpenGlasses-MC1.12.2-2.2-50)
 - Botania (Botania r1.10-363)

**Additional context**
I am sorry if the code is incomplete.
Since it uses Google Translate, it may be difficult to read, but thank you

**Comment by ghost** [comment]
The same phenomenon was confirmed in Item3D,
It was confirmed that crash does not occur if the meta number is set to a value other than 0.
![2020-06-07_16 52 26](https://user-images.githubusercontent.com/66514293/83963248-73ab4900-a8df-11ea-9da2-664fe29ec15f.png)

**Comment by ben-mkiv** [comment]
fix is in commons0815/rendertoolkit, prebuild can be found here, next release on curseForge will have the fix:
https://github.com/Starchasers/OCGlasses/blob/OG2-MC1.12.2/libs/Commons0815-1.12.2-1.3.8.jar
